# Generated by Django 4.1.4 on 2024-02-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_room_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='owner',
        ),
    ]
